German Luppp translation
georgkrause/manual pull request #1
Opened 2017-04-28 17:29 UTC by coderkun

Translate the Luppp manual into German using the file “de-luppp.rst”. Please read and review.

2017-04-28 17:30 UTC, coderkun commented
Not complete, yet, so please wait with merging.

2017-04-29 10:20 UTC, coderkun commented
The Luppp translation is complete now. @georgkrause, please review.

2017-04-29 12:18 UTC, georgkrause commented
@coderkun Thanks for Your work. Sadly i am I'll and away from my devices so this will take some time. I hope I can do it next week.

2017-04-29 12:19 UTC, georgkrause commented
*ill. Funny Auto correction :D

2017-05-01 11:23 UTC, georgkrause commented
@coderkun i would suggest to change this in order to fit your issues. eg replace all "we"s with "you". Or do you think its better to keep it with the original english version?

2017-05-01 11:29 UTC, coderkun commented
@georgkrause, I would like to do this as separate steps:

1. Merge the current German translation
2. Fix the wording in the English version (if @harryhaaren agrees to this change, it is currently only a suggestion)
3. Update the German translation to reflect the English wording

2017-05-01 11:33 UTC, harryhaaren commented
Yep whatever suits you guys best - both OK with me!

2017-05-01 11:39 UTC, georgkrause requested changes
I added some comments what could be changed, please review!
Why are there changes in the luppp.rst? This shouldnt be part of this PR

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Szenen und Clips vorgestellt, sodass die Kreativität für Live-Auftritte optimal
"sodass du deiner Kreativität freien Lauf lassen kannst" ?

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Bevor wir Loops aufnehmen können, müssen wir eine Audioquelle mit Luppps
"Bevor du Loops aufnehmen kannst"

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Als nächstes schauen wir uns die Oberfläche von Luppp an. Diese mag auf den
"Schau dir nun die Oberfläche von Luppp an"

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +funktioniert, spiele deine Audioquelle ab und du solltest die Amplitude auf der
statt Amplitude eventuell Ausschlag? oder Pegel? Das klingt weniger technisch

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +ein Clip zur gleichen Zeit agbespielt werden. Im Masterbereich von Luppp
"abgespielt" ;)

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Mix zu geben. Das ist sehr simple, gehen wir also weiter …
"simpel"

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Bearbeitung zu aktivieren, klicke auf die gelbe FX-Schaltfläche. Mit dem
"Bearbeitung" erscheint mir hier nicht als das richtige Wort, eine bessere Idee habe ich aber leider auch nicht :(

2017-05-01 11:39 UTC, georgkrause commented on source/de-luppp.rst
> +Komma getrennt ngegeben werden::
"angegeben"

2017-05-01 11:40 UTC, georgkrause commented
@coderkun i am okay with your workflow, so lets keep it according to the english wording.

2017-05-01 13:13 UTC, coderkun commented on source/de-luppp.rst
> +Szenen und Clips vorgestellt, sodass die Kreativität für Live-Auftritte optimal
Much better, yes.

2017-05-01 13:13 UTC, coderkun commented on source/de-luppp.rst
> +Bevor wir Loops aufnehmen können, müssen wir eine Audioquelle mit Luppps
Sounds better, I agree.

2017-05-01 13:14 UTC, coderkun commented on source/de-luppp.rst
> +Als nächstes schauen wir uns die Oberfläche von Luppp an. Diese mag auf den
Agreed.

2017-05-01 13:15 UTC, coderkun commented on source/de-luppp.rst
> +funktioniert, spiele deine Audioquelle ab und du solltest die Amplitude auf der
In diesem Fall finde ich „Ausschlag“ am verständlichsten.

2017-05-01 13:16 UTC, coderkun commented on source/de-luppp.rst
> +ein Clip zur gleichen Zeit agbespielt werden. Im Masterbereich von Luppp
Typo, right.

2017-05-01 13:16 UTC, coderkun commented on source/de-luppp.rst
> +Mix zu geben. Das ist sehr simple, gehen wir also weiter …
Typo, right.

2017-05-01 13:17 UTC, coderkun commented on source/de-luppp.rst
> +Bearbeitung zu aktivieren, klicke auf die gelbe FX-Schaltfläche. Mit dem
Vielleicht einfach „Um den Effekt zu nutzen, klick auf […]“?

2017-05-01 13:18 UTC, coderkun commented on source/de-luppp.rst
> +Komma getrennt ngegeben werden::
Typo, right.

2017-05-01 13:19 UTC, georgkrause commented on source/de-luppp.rst
> +Bearbeitung zu aktivieren, klicke auf die gelbe FX-Schaltfläche. Mit dem
klingt gut.

2017-05-01 15:53 UTC, coderkun reviewed
Requested changes have been pushed with commit 6aee873.

2017-05-21 08:59 UTC, coderkun commented
@georgkrause, is this PR complete or is anything missing?

2017-05-21 12:15 UTC, georgkrause commented
@coderkun oh sorry, i totally missed this! i will look about it now

2017-05-21 12:17 UTC, georgkrause approved these changes

2017-05-21 12:17 UTC, merged